/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_kp_rtspcamera_poker_NativePoker */

#ifndef _Included_de_kp_rtspcamera_poker_NativePoker
#define _Included_de_kp_rtspcamera_poker_NativePoker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_kp_rtspcamera_poker_NativePoker
 * Method:    DecodePicture
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_de_kp_rtspcamera_poker_NativePoker_DecodePicture
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
